# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_dual2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_dual2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_dual2_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_upperArm_joint
      - left_foreArm_joint
      - left_wrist1_joint
      - left_wrist2_joint
      - left_wrist3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_dual2_controller:
  ros__parameters:
    joints:
      - right_shoulder_joint
      - right_upperArm_joint
      - right_foreArm_joint
      - right_wrist1_joint
      - right_wrist2_joint
      - right_wrist3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity