# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_dual2_controller
    - right_dual2_controller

  left_dual2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_shoulder_joint
      - left_upperArm_joint
      - left_foreArm_joint
      - left_wrist1_joint
      - left_wrist2_joint
      - left_wrist3_joint
  right_dual2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_shoulder_joint
      - right_upperArm_joint
      - right_foreArm_joint
      - right_wrist1_joint
      - right_wrist2_joint
      - right_wrist3_joint